[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pacmof2"
version = "1.0.0"
authors = [
  { name="Thang Pham", email="thangpham2024@u.northwestern.edu" },
]
dependencies = [
    "ase>=3.22.1",
    "pymatgen>=2023.10.4",
    "scikit-learn==1.3.2",
    "tqdm>=4.15",
    "huggingface-hub>=0.20",
]
description = "Predicting partial atomic charges in Metal-Organic Frameworks with DFT-level accuracy"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
pacmof2 = "pacmof2.cli:main"
pacmof2-download-models = "pacmof2.cli:download_models_main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["pacmof2*"]
